### ISSUE TITLE
error : 6: function: not found (on Voidlinux)

### ISSUE THREAD

**Issue by lystymoi** [bubbleguuum/toggle-monitor-grayscale#4]
On voidlinux script gives an error : 6: function: not found

But it works on other distributions.
What may be the reason?

`sh toggle-monitor-grayscale.sh picom
toggle-monitor-grayscale.sh: 6: function: not found

Toggle monitors between color and grayscale mode.

toggle-monitor-grayscale.sh [picom|nvidia|ddc|auto]
toggle-monitor-grayscale.sh picom [picom args]
toggle-monitor-grayscale.sh nvidia [nv mon]
toggle-monitor-grayscale.sh ddc [ddc mon]

picom:   use a GLX shader to set grayscale
nvidia:  use NVIDIA proprietary driver Digital Vibrance setting to set grayscale
ddc:     use DDC/CI monitor protocol to set the monitor saturation to 0 (grayscale) if supported by monitor
auto:    use picom if running, otherwise nvidia if available, otherwise ddc if available

picom args: in picom mode, optional picom parameters

nv mon:     in nvidia mode, an optional monitor name as enumerated by xrandr.
            if unspecified, apply to all monitors managed by the NVIDIA driver
ddc mon:    in ddc mode, optional ddcutil options to identify the monitor. See 'man ddcutil'
            if unspecified, apply to the first monitor detected by ddcutil
if invoked with no argument, auto is used.
`

**Comment by bubbleguuum** [comment]
You get this error because it it is a bash script and I suppose the `sh toggle-monitor-grayscale.sh` tries to run it with another shell.
Instead and assuming you have bash installed (`/bin/bash`), run it this way:

make the script executable if necessary (only needed once):
`chmod +x toggle-monitor-grayscale.sh`

run it with (if in your `PATH`):
`toggle-monitor-grayscale.sh`

or 
`/path/to/toggle-monitor-grayscale.sh`

**Comment by lystymoi** [comment]
Hi. Thanks for the fast reply.
Yes I found that unlike on other distributions on Void sh is not linked to bash.
When you enter sh it is actually /bin/sh that does not understand bash syntas such "function"
When I execute script with path or bash it works. )
